# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: right hemisphere
email: to.right.hemisphere@gmail.com
author: Nicholas Rasi
description: > # this means to ignore newlines until "baseurl:"
  Right Hemisphere site by Nicholas Rasi. Video and Music Production
baseurl: "" # the subpath of your site, e.g. /blog
url: "righthemisphere.it" # the base hostname & protocol for your site
repository: https://makebit.github.io/right-hemisphere/

github_username:  makebit

# Build settings
markdown: kramdown


exclude:
- ".gitignore"
- CNAME
- assets/vendor/parallaxjs/README.md
- readme.md